import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import OfflineSyncProvider from "@/components/OfflineSyncProvider";

const neulis = localFont({
  src: [
    {
      path: "./fonts/neulis/Neulis-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/neulis/Neulis-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/neulis/Neulis-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/neulis/Neulis-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/neulis/Neulis-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-display",
  display: "swap",
});

const helvetica = localFont({
  src: [
    {
      path: "./fonts/helvetica/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/helvetica/Helvetica-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/helvetica/Helvetica-Oblique.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/helvetica/Helvetica-BoldOblique.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Macost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${neulis.variable} ${helvetica.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <OfflineSyncProvider />
        {children}
      </body>
    </html>
  );
}
